### PR TITLE
Introduce Record `.pick` and `.omit`

### PR DESCRIPTION
**Pull request by ivawzh**
To help DRYing runtype declarations and better reflect cross data type relationships. 

Method names are following TypeScript built-in mapped type `Omit<>` and `Pick<>` naming conventions.

Close: https://github.com/pelotom/runtypes/issues/148

### CODE REVIEW

**Comment by reinismu** [comment]
This is super awesome! Any reason not to merge it? :)

**Comment by ivawzh** [comment]
@reinismu this repo seems quite inactive. FYI, you may want to try io-ts.

**Comment by ivawzh** [comment]
PR is merged at https://github.com/ForbesLindesay/funtypes/pull/38

**Comment by yuhr** [comment]
Worth reopening now 😉

**Comment by ivawzh** [comment]
Hi @yuhr 
I am curious what happened to the previously merged PR https://github.com/ForbesLindesay/funtypes/pull/38? Has it got rolled back?

**Comment by yuhr** [comment]
@ivawzh Sorry I don't know well about `funtypes`, I just reopened this as part of resurrection of `runtypes` maintainance. You should ask in that repository.

**Comment by ivawzh** [comment]
I see. I was confused by the library names. I thought this PR was merged to runtype already 🤦‍♂️ 

Thanks for reopening.

**Comment by yuhr** [comment]
Seems like we don't need splitting the code into util.ts, as these functions is only used within record.ts. Let me add some commits.

**Comment by yuhr** [comment]
Though this is just a stylistic decision, I'd rather use arbitrary length parameters instead of a single array input, to be consistent with existing APIs such as `Union` and `Intersect`.

**Comment by ivawzh** [comment]
Nice and clean. Thanks for merging it @yuhr

**Pull request merged**
