### PR TITLE
Add Struct and Maybe types

### PR DESCRIPTION
**Pull request by yosbelms**
`Struct` is an extension of `Record` that sets optional properties of `Maybe` type.

```ts
const User = Struct({
  id: Maybe(Number),
  name: String,
})
```

Equivalences:

`Maybe(T)` == `Union(T, Undefined)`
`Struct({ opt: Maybe(O), req: R })` == `Record({ req: R }).And(Partial({ opt: O }))`

Additionally the `eval` utility does the same that `check` but also check types at compile time.
```ts
const user = User.eval({
  id: 'invalid'
})

// Error...
```

### CODE REVIEW

**Comment by ben-pr-p** [comment]
Definitely like the `key: Maybe(O)` over `.and(Partial(...`!

**Comment by yosbelms** [comment]
@ben-pr-p if you want to try it the npm package is `yosbelms-runtypes`

**Comment by nebur395** [comment]
Hey guys,
Awesome repository by the way, thank you for your work.
I'd really love something like this. Is it possible to boost the review of this PR?
Thank you :)

**Comment by pelotom** [comment]
This is an interesting approach. Why is the `Struct` type needed, instead of just augmenting `Record`?

**Comment by yuhr** [comment]
Ping @yosbelms. I'm wondering the same thing too. I'm very keen to merge `Maybe` only.

**Comment by yuhr** [comment]
Let's close in favor of #113, where the problem is better explained.

**Pull request closed without merging**
